#!/usr/bin/env python3
"""Generate the op-coverage matrix doc from real zoo exports.

Follows SiMa ``build_supported_operators_md.py`` in structure — an
AUTO-GENERATED markdown table — but the source of truth is **our measured
torch-dialect IR**, not a hardware datasheet. Each zoo op is exported, its
aten-op histogram collected, and a model×op matrix written to
``docs/generated/op-coverage.md`` with an on-device audit verdict per model.

Run (inside venv-shark):
    python scripts/build_op_coverage.py
"""
from __future__ import annotations

import json
from pathlib import Path

import torch

from torch_mlir_zoo import export_for_npu
from torch_mlir_zoo.analysis import SUPPORTED_ATEN_OPS, audit
from torch_mlir_zoo.ops import RMSNorm, ScaledDotProductAttention, SwiGLU, TopK

MODELS = {
    "attention": (ScaledDotProductAttention, (1, 32, 512)),
    "rmsnorm": (RMSNorm, (1, 32, 512)),
    "mlp": (SwiGLU, (1, 32, 512)),
    "topk": (TopK, (1, 32000)),
}

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated" / "op-coverage.md"
# Whole HF checkpoints are not re-exported here (1B+ models); the sweep writes
# their histograms and this doc reads them.
SWEEP = ROOT / "logs" / "hf-zoo" / "results.json"


def collect() -> tuple[dict[str, dict[str, int]], dict[str, dict]]:
    counts: dict[str, dict[str, int]] = {}
    verdicts: dict[str, dict] = {}
    for name, (factory, shape) in MODELS.items():
        r = export_for_npu(factory(), (torch.randn(*shape),), backend="iree_turbine")
        counts[name] = r.summary["op_counts"]
        verdicts[name] = audit(r.mlir)

    if SWEEP.exists():
        for row in json.loads(SWEEP.read_text())["results"]:
            if row["status"] != "ok":
                continue
            counts[row["name"]] = row["op_counts"]
            # Re-judge against the current allowlist rather than trusting the
            # verdict stored at sweep time — the allowlist grows as ops certify.
            unknown = set(row["op_counts"]) - set(SUPPORTED_ATEN_OPS)
            verdicts[row["name"]] = {
                "unique_ops": row["unique_aten_ops"],
                "ok": not unknown and not row["server_side_op_hits"],
            }
    return counts, verdicts


def render(counts: dict[str, dict[str, int]], verdicts: dict[str, dict]) -> str:
    models = list(counts)
    all_ops = sorted({op for c in counts.values() for op in c})
    lines = [
        "<!-- AUTO-GENERATED by scripts/build_op_coverage.py — do not edit by hand -->",
        "# Op coverage",
        "",
        "Each cell is the op count in that model's exported torch-dialect MLIR "
        "(backend `iree_turbine`). `on-device` is the audit verdict — no server-side "
        "ops and every op on the allowlist.",
        "",
        "| aten op | on allowlist | " + " | ".join(models) + " |",
        "|---|:--:|" + "|".join([":--:"] * len(models)) + "|",
    ]
    for op in all_ops:
        flag = "✅" if op in SUPPORTED_ATEN_OPS else "❓"
        cells = " | ".join(str(counts[m].get(op, "·")) for m in models)
        lines.append(f"| `{op}` | {flag} | {cells} |")
    lines += ["", "## Verdict", "", "| model | unique ops | on-device |", "|---|:--:|:--:|"]
    for m in models:
        v = verdicts[m]
        lines.append(f"| {m} | {v['unique_ops']} | {'✅ OK' if v['ok'] else '❌ FAIL'} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    counts, verdicts = collect()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(counts, verdicts))
    print(f"wrote {OUT} ({len(counts)} models, {sum(len(c) for c in counts.values())} op-cells)")


if __name__ == "__main__":
    main()
